export const Colors = {
  primary: '#5B4FE9',
  primaryDark: '#4038C8',
  primaryLight: '#EEEEFF',
  income: '#34C85A',
  incomeLight: '#E8FAEE',
  expense: '#FF453A',
  expenseLight: '#FFF0EF',
  background: '#F2F2F7',
  card: '#FFFFFF',
  textPrimary: '#1C1C1E',
  textSecondary: '#8E8E93',
  textLight: '#C7C7CC',
  border: '#E5E5EA',
  white: '#FFFFFF',
} as const;
